---
default_stages:
  - commit

default_install_hook_types:
  - commit-msg
  - pre-commit
  - prepare-commit-msg

exclude: "^docs/|^CHANGELOG.md$"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        exclude: "^project/"

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.38.0"
    hooks:
      - id: markdownlint-fix
        name: markdownlint

  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.33.0"
    hooks:
      - id: yamllint
        entry: yamllint --strict

  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: "v2.1.0"
    hooks:
      - id: shell-fmt-go

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.9.0.6"
    hooks:
      - id: shellcheck

  - repo: https://github.com/rhysd/actionlint
    rev: "v1.6.26"
    hooks:
      - id: actionlint
